name: Execute python
on:
  workflow_call

jobs:
  run-script:
    environment: Training
    runs-on: ubuntu-latest

    steps:
    - name: checkouit this repo
      uses: action/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-versions: '3.x'

    - name: Run python
      run:  |
          python script.py
